insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'FILMES','Return of the Jedi', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'FILMES','Return of the Jedi', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'FILMES', 'The Empire Strikes Back', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'FILMES', 'A New Hope', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'C-3PO', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'C-3PO', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( next value for seq_estatistica, 'PERSONAGENS', 'R2-D2', trunc(SYSDATE) );