insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 1, 'FILMES','Return of the Jedi', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 2, 'FILMES','Return of the Jedi', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 3, 'FILMES', 'The Empire Strikes Back', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 4, 'FILMES', 'A New Hope', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 5, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 6, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 7, 'PERSONAGENS', 'Luke Skywalker', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 8, 'PERSONAGENS', 'C-3PO', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values ( 9, 'PERSONAGENS', 'C-3PO', trunc(SYSDATE) );
insert into estatistica (id_estatistica, tp_consulta, st_termo, dt_consulta) values (10, 'PERSONAGENS', 'R2-D2', trunc(SYSDATE) );